### ISSUE TITLE
[FEAT] - Realtime Events for Follow, Gather & Goto

### ISSUE THREAD

**Issue by vincent-the-boundary** [SuperViz/sdk#193]
**Is your feature request related to a problem? Please describe.**
The realtime events are not hooked up to publish events for gather all and follow

**Describe the solution you'd like**
I'd like to see REALTIME_GATHER and REALTIME_FOLLOW_USER be hooked up to publish when the user clicks gather all or follow. communicator/index.ts line 314-324

```
  private onFollowUserDidChange = (userId: string | null): void => {
    this.realtime.setFollowUser(userId);
    this.publish(RealtimeEvent.REALTIME_FOLLOW_USER,userId);
  };

  private onGoToUserDidChange = (userId: string): void => {
    this.integrationManager.goToUser(userId);
    this.publish(RealtimeEvent.REALTIME_GO_TO_USER,userId);
  };

  private onGatherDidChange = (): void => {
    this.realtime.setGather(true);
    this.publish(RealtimeEvent.REALTIME_GATHER,true);
  };
```

**Describe alternatives you've considered**
Another more involved solution would be to allow consumers of this sdk to build the call UI themselves and expose functions to gather, follow and goTo on the sdk.

**Additional context**
Our use case for needing this is that our web solution uses our own custom build adapter. The reason being our camera animations and navigational controls are non standard. to trigger those transitions correctly for gather, goto and follow we need access to when those buttons have been pressed.

**Comment by tommy-superviz** [comment]
Hi @vincent-the-boundary 

Thank you for the detailed description.

We can definitely make the Gather, Follow and GoTo public. I will add this to our task list and inform you of the timeline once our next sprint has been planned.

Regarding UI elements, custom themes are something that is coming up sometime next month. We are planning for you to be able to change the colour scheme, sizes and icons.

**Comment by tommy-superviz** [comment]
Hi @vincent-the-boundary 

The feature request you raised has been deployed. You can find it in version 3.2.2. 

You can find the documentation of the listers and methods in our documentation: https://docs.superviz.com/SDK/api-reference
