### ISSUE TITLE
Three.js adapter 1.0

### ISSUE THREAD

**Issue by SuperViz-Dev** [SuperViz/sdk#20]
The Three.js adaptor will SuperViz-enable 3D viewers using three.js 

Features included:

- Inject avatars
- Custom avatars (GTLF and GLB support)
- Follow a participant
- Gather all participants
- Goto a participant

References:
https://threejs.org/

**Comment by vincent-the-boundary** [comment]
I second this. Heck I'd even build it. Does anyone know how to build these adapters? Could not find it in the docs.

**Comment by tommy-superviz** [comment]
Hi Vincent, the team is working hard on the adapters so hopefully this should be coming soon. We are just about to launch the Matterport adapter and the threeJs will be next in line. We'll keep you posted on the progress.

**Comment by vincent-the-boundary** [comment]
Hey just checking in to see if this adapter is available and documented?

**Comment by tommy-superviz** [comment]
Hi @vincent-the-boundary. Great timing 👍 
We will launch the three.js adaptor by next week together with our official launch.

**Comment by vincent-the-boundary** [comment]
Sound sweet! What day will the new version go live?
In the meantime maybe you can help me out with something. 
Are there any events to listen to for when a user clicks on gather or follow?

**Comment by tommy-superviz** [comment]
@vincent-the-boundary this one as ready and a part of v. 3.0.0
