### ISSUE TITLE
Guide Chief

### ISSUE THREAD

**Issue by Abethebabe91** [SuperViz/sdk#58]
When working with multiple guides and clients it can be helpful to delegate virtual tours to guides for specific audiences

Create an administrative role on Superviz that can delegate tours to guides or assign guides to specific tours

At the moment with one account it is possible to switch in and out with different guides, but if multiple tours are happening, or a tour needs to be tailored for a specific audience or the guide is new to the system, it can be very helpful to have a system of assignment for an administrator.

**Comment by tommy-superviz** [comment]
Thanks for bringing this up.

This request is related to our web app and not our SDK. I'll send the request to our product team. 

With the current SDK version, you are able to delegate Hosts, etc. but it needs to be implemented on your end.
