### ISSUE TITLE
integrate with GoDaddy

### ISSUE THREAD

**Issue by Ahmedeissagom** [SuperViz/sdk#672]
How can I integrate an SDK and API into my GoDaddy website?

**Comment by vtnorton** [comment]
Hi @Ahmedeissagom, I saw that you can [add personalized JavaScript and HTML to you GoDaddy](https://www.godaddy.com/help/add-html-or-custom-code-to-my-site-27252) website, and with that you can use our SDK with CDN. 

One of the options to use our SDK, besides using it as a package, is usage with a Content Delivery Network, or CDN. This means that you are importing our SDK with a `script` tag. You can do that with the following line added to your HTML (we recommend adding it inside the `<head>`):

```html
<script type="module" src="https://unpkg.com/@superviz/sdk@latest"></script>
```

We have a dedicated page on our documentation with [detailed instructions on how to use our SDK as a CDN](https://docs.superviz.com/guides/misc/using-as-a-cdn), including the technical differences from using it as a package, and how to adapt the examples and explanations given in this documentation for a CDN context.

I invite you to use [our Discord server](https://discord.gg/NJqBaQhY2s), so I can better assist you if you'd need anything else.
